#!/bin/bash

###############################################
#Author: Brian Hoglan                         #
#Email: bhoglan@gmail.com                     #
#Created Date: 2022/09/11                     #
#Updated:                                     #
#Version: 1.0                                 #
###############################################
# v 1.0 - Initial script creation.

###############################################
#This is a script to backup the Bookstack DB. #
# 1. Perform a mysqldump of the Bookstack DB  #
# container.                                  #
#  A. mysqldump uses .mylogin.cnf generated by#
# mysql_config_editor.                        #
# 2. Dump is placed in                        #
# $DOCKERDIR/appdata/mariadb/archive for      #
# handling by                                 #
# $DOCKERDIR/shared/bookstackbackup.sh        #
###############################################

#crontab entries
#0 0 * * * /archive/dbbackup.sh
#0 12 * * * /archive/dbbackup.sh

#Set variables
date=$(date +"%y%m%d-%H%M")
db_filename=${date}"-bookstack_db.sql"

#Dump the database to a file
mysqldump --defaults-file=.mycreds.cnf --all-databases > $db_filename

#Write a log entry
echo -e "\xE2\x9C\x85" ${date} "\\\ Bookstack DB backed up successfully!" ${db_filename} "\xE2\x9C\x85" >> /archive/archive.log
